# Generated by Django 5.2 on 2025-04-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_activelead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activelead',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='activelead',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activelead',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='activelead',
            name='created_by',
        ),
    ]
