# Generated by Django 5.2 on 2025-04-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_activelead_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contract', verbose_name='Контракт')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.lead', verbose_name='Потенциальный клиент')),
            ],
            options={
                'verbose_name': 'Активный клиент',
                'verbose_name_plural': 'Активные клиенты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ActiveLead',
        ),
    ]
